language: go
go:
  - "1.11"
env:
  - CODECOV_TOKEN="dfe8163e-dd0c-4c2e-9c62-bce7a87eeeff"
  - GO111MODULE=on
  - API=slate
  - API_PATH=./cmd/${API}
before_install:
  - export
install:
  - go get -u github.com/mgechev/revive
before_script:
  - go fmt ${API}/...
  - go vet -mod vendor ${API}/...
  - revive -formatter stylish -config ./configs/revive.toml -exclude ./vendor/... ./...
  - go test -mod vendor ${API}/...
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ${API}/...
  - go build -mod vendor -o ./bin/slate ${API_PATH}/...
after_success:
  - bash <(curl -s https://codecov.io/bash)
