language: go
go:
  - "1.11.2"
script:
  - go vet -mod=vendor ./cmd/slate/...
  - revive -formatter stylish -config ./config/revive.toml -exclude ./vendor/... ./...
  - go test -mod=vendor ./cmd/slate/...
  - build -mod=vendor -o bin/slate ./cmd/slate/...
