language: go
go:
  - "1.11"
before_install:
  - export GO111MODULE=on
install:
  - go get -u github.com/mgechev/revive
before_script:
  - go vet -mod vendor ./cmd/slate/...
  - revive -formatter stylish -config ./config/revive.toml -exclude ./vendor/... ./...
  - go test -mod vendor ./cmd/slate/...
script:
  - go build -mod vendor -o ./bin/slate ./cmd/slate/...
