language: go
go:
  - "1.11"
install:
  - ls -al
  - go vet ./cmd/slate/...
  - revive -formatter stylish -config ./config/revive.toml -exclude ./vendor/... ./...
  - go test ./cmd/slate/...
script:
  - build -o bin/slate ./cmd/slate/...
