language: go
go:
  - "1.11"
env:
  - CODECOV_TOKEN="dfe8163e-dd0c-4c2e-9c62-bce7a87eeeff"
before_install:
  - export GO111MODULE=on
install:
  - go get -t -v ./...
  - go get -u github.com/mgechev/revive
before_script:
  - go vet -mod vendor ./cmd/slate/...
  - revive -formatter stylish -config ./configs/revive.toml -exclude ./vendor/... ./...
  - go test -mod vendor ./cmd/slate/...
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  - go build -mod vendor -o ./bin/slate ./cmd/slate/...
after_success:
  - bash <(curl -s https://codecov.io/bash)
